modLoader="javafml"
loaderVersion="[35,)"
license="Academic Free License v3.0"

[[mods]]
modId="toffiumforge"
version="1.0.0"
displayName="Toffium-forge"
credits="Mod dodajacy nowe bloki i zwierzeta, wiecej zmian pozniej"
displayURL="github.com/tofikarz/Toffium-forge"
authors="ChaeYox (tofikarz)"

[[dependencies.toffiumforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




