modLoader="javafml"
loaderVersion="[35,)"
license="MIT License"

[[mods]]
modId="toffiumforge"
version="1.16.4"
displayName="Toffium-forge"
credits=""
displayURL="https://github.com/tofikarz/Toffium-forge"
authors="ChaeYox (tofikarz)"

[[dependencies.toffiumforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




