modLoader="javafml"
loaderVersion="[35,)"
license="MIT License/Licencja"

[[mods]]
modId="toffiumforge"
version="1.0.1"
displayName="Toffium-forge"
credits="Mod jest open-source , czyli ka¿dy kto chce mo¿e daæ pomys³ co jeszcze dodaæ <3"
displayURL="https://github.com/tofikarz/Toffium-forge"
authors="ChaeYox (tofikarz)"

[[dependencies.toffiumforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




