name: C2ME Build Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Ustaw JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        
    - name: Skompiluj modyfikacje
      run: | 
           ./gradlew processResources
           ./gradlew classes 
           ./gradlew jar 
           ./gradlew downloadMcpConfig 
           ./gradlew extractSrg 
           ./gradlew createMcpToSrg
           ./gradlew reobfJar 
           ./gradlew assemble 
           ./gradlew compileTestJava
           ./gradlew processTestResources
           ./gradlew testClasses
           ./gradlew test 
           ./gradlew check
           ./gradlew build
           ./gradlew clean build
        
    - name: Udostępnij artefakt
      uses: actions/upload-artifact@v2
      with:
        name: toffium-forge-1.16.5
        path: '**/build/libs/*.jar'
      
